# Binary Search

- Provides efficient way to find a target value within a sorted array.
- It repeatedly divides the search interval in half, which makes it far faster than a linear search for large datasets.

Receipe:
1. Prerequisite: The array must be sorted.
2. Concept: We have two pointers, left and right, which represent the current search range.
3. Midpoint Calculation: Calculate the middle index of the current range.
4. Comparison:
- If the element at mid equals the target, we’ve found the element, and we can return the index.
- If the element at mid is less than the target, we move left to mid + 1, narrowing the search to the right half.
- If the element at mid is greater than the target, we move right to mid - 1, narrowing the search to the left half.
5. End Condition: Repeat until left exceeds right. If we haven’t found the target by then, it means the target is not in the array.

In [8]:
def binary_search(arr, target):
    # the arr has to be sorte 
    left = 0
    right = len(arr)-1
    
    while left<=right:  
        mid = (right-left)//2 + left
    
        if target==arr[mid]:
            return mid
        elif target<arr[mid]:
            right = mid - 1 
        else:
            left = mid + 1 

        
    return "Not in the list"    

In [7]:
arr = [1, 3, 5, 7, 9, 11, 13]

# print(binary_search(arr, 7))   # Output should be 3
print(binary_search(arr, 10))  # Output should be -1 (not found)

Not in the list


# Bubble Sort

1. Start with the first element and compare it to the next one.
2. If the first element is larger than the next one (for ascending order), swap them.
3. Move to the next pair of adjacent elements, and repeat the comparison and swap if needed.
4. Continue this process until you reach the end of the list. At this point, the largest element will be in its correct position (at the end).
5. Repeat steps 1-4 for the remaining unsorted part of the list (ignoring the last sorted elements).
6. Continue until the list is fully sorted.

Bubble Sort stops when it completes a pass without any swaps, which means the list is sorted.

In [39]:
def BubbleSort(arr):
    n = len(arr)
    for i in range(n):
        swapped = False
        for ii in range(0, n-1-i): # Only loop through unsorted portion
            if arr[ii] > arr[ii+1]:
                arr[ii], arr[ii+1] = arr[ii+1], arr[ii]
                swapped = True 
        if not swapped:
            return arr

In [43]:
import unittest

class TestBubbleSort(unittest.TestCase):
    
    def test_basic_unsorted_list(self):
        arr = [5, 3, 8, 4, 2]
        expected = [2, 3, 4, 5, 8]
        self.assertEqual(BubbleSort(arr), expected)
        
    def test_already_sorted_list(self):
        arr = [1, 2, 3, 4, 5]
        expected = [1, 2, 3, 4, 5]
        self.assertEqual(BubbleSort(arr), expected)
        
    def test_reverse_sorted_list(self):
        arr = [5, 4, 3, 2, 1]
        expected = [1, 2, 3, 4, 5]
        self.assertEqual(BubbleSort(arr), expected)
        
    def test_list_with_duplicates(self):
        arr = [4, 3, 4, 1, 2]
        expected = [1, 2, 3, 4, 4]
        self.assertEqual(BubbleSort(arr), expected)
        
    def test_single_element_list(self):
        arr = [42]
        expected = [42]
        self.assertEqual(BubbleSort(arr), expected)
        
    # def test_empty_list(self):
    #     arr = []
    #     expected = []
    #     self.assertEqual(BubbleSort(arr), expected)
        
    def test_large_random_list(self):
        import random
        arr = random.sample(range(1, 100), 15)  # 15 unique random numbers from 1 to 100
        expected = sorted(arr)  # Python's built-in sorted function for expected result
        self.assertEqual(BubbleSort(arr), expected)

    def test_large_identical_elements(self):
        arr = [7] * 10  # List with 10 identical elements
        expected = [7] * 10
        self.assertEqual(BubbleSort(arr), expected)

# Run the tests
unittest.main(argv=[''], verbosity=2, exit=False)


test_already_sorted_list (__main__.TestBubbleSort.test_already_sorted_list) ... ok
test_basic_unsorted_list (__main__.TestBubbleSort.test_basic_unsorted_list) ... ok
test_large_identical_elements (__main__.TestBubbleSort.test_large_identical_elements) ... ok
test_large_random_list (__main__.TestBubbleSort.test_large_random_list) ... ok
test_list_with_duplicates (__main__.TestBubbleSort.test_list_with_duplicates) ... ok
test_reverse_sorted_list (__main__.TestBubbleSort.test_reverse_sorted_list) ... ok
test_single_element_list (__main__.TestBubbleSort.test_single_element_list) ... ok

----------------------------------------------------------------------
Ran 7 tests in 0.011s

OK


# Insertion Sort

1. Start from the second element (since a single-element array is already sorted) and iterate through the array.
2. Compare the current element with elements in the sorted portion to its left.
3. Shift elements of the sorted portion to the right until the correct position for the current element is found.
4. Insert the current element into its correct position.
5. Repeat for all elements until the array is sorted.

In [31]:
# it might be incorect 

def insertion_sort(arr):
    for i in range(1, len(arr)):
        j = i-1
        while j>=0 and arr[i] < arr[j]:
            arr[j], arr[i] = arr[i], arr[j]
            j -= 1
            i -= 1 
            print(arr,i,j)
    return arr

In [30]:
ar = [3, 1, 6, 9, 5, 7]

insertion_sort(ar)

[1, 3, 6, 9, 5, 7] 0 -1
[1, 3, 6, 5, 9, 7] 3 2
[1, 3, 5, 6, 9, 7] 2 1
[1, 3, 5, 6, 7, 9] 4 3


[1, 3, 5, 6, 7, 9]

# Merge Sort

The main idea behind Merge Sort is to break the array down into smaller sub-arrays until each sub-array has only one element (which is by definition sorted), and then merge these sub-arrays back together in the correct order.

Here's a step-by-step explanation:

1. Divide: Split the array into two halves.
2. Conquer: Recursively sort each half.
3. Combine: Merge the two sorted halves to form a single sorted array.

In [ ]:
def mergeSort(arr):

    arrLen = len(arr)
    
    if arrLen<=1:
        return arr

    left_half = arr[:arrLen]
    right_half = arr[arrLen:]
    mergeSort(left_half)
    mergeSort(right_half)

    return merge(left_half, right_half)

def merge(leftArr, rightArr):
    mArr = []
    

In [ ]:
my_array = [64, 34, 25, 12, 22, 11, 90, 5]
start = 0
end = len(my_array)-1
quick_sort(my_array, start, end)
print("Sorted array:", my_array)

# Quick Sort

Quick Sort is a divide-and-conquer algorithm that sorts an array by partitioning it into two smaller sub-arrays:
- Elements less than a chosen pivot element.
- Elements greater than the pivot element.

How Quick Sort Works
Here's a step-by-step breakdown of the Quick Sort algorithm:

1. Choose a Pivot Element:
<br>
The pivot can be any element in the array. Common strategies include picking the first element, the last element, a random element, or the median. <br>
3. Partition the Array:
<br> Rearrange the array such that all elements less than the pivot are on the left, and all elements greater than the pivot are on the right. The pivot element is then placed in its correct sorted position. <br>
5. Recursively Apply Quick Sort:
<br> Apply Quick Sort to the left sub-array (elements less than the pivot) and the right sub-array (elements greater than the pivot). <br>


In [24]:
# Simple - Without repetition

def quick_sort(arr):

    if len(arr) <= 1:
        return arr

    pivot = arr[-1]

    left = [x for x in arr if x<pivot]
    right = [x for x in arr if x>pivot]

    return quick_sort(left) + [pivot] + quick_sort(right)

In [34]:
# more complicated but more efficent

def parition(arr, start, end):
    # choose the right most element
    pivot = arr[end]

    # 'i' is used as a boundary pointer to separate elements that are less than or equal to the pivot from those that are greater.
    # We start `i` at `low - 1`
    # This is because, initially, no elements have been found that are less than or equal to the pivot, so 'i' points to a position before the low index.
    i = start-1

    # Loop through each element from `low` to `high - 1`
    
    # This loop goes by all elements of the array. 
    # If the current element is equal or lower than the pivot element we increase 'i'.
        # 'i' is the pointer which points to the last element in the array we loop which points to ' < pivot'
    # Else 'i' is still pointing to the element lower than pivot
    # Than if we find later the element <= pivot 
    # we swap it with the next element higher than 'i'
    # and we continue 
    for j in range(start, end):
        
        # If the current element `array[j]` is less than or equal to the pivot
        # it should be on the left side of the pivot. 
        if arr[j] <= pivot:
            i += 1 
            # print('Before swap', arr, i, j, arr[j], arr[i])
            (arr[i], arr[j]) = (arr[j], arr[i])
            # print('After swap', arr, i, j, arr[j], arr[i])

    # At the end we swap the pivot element with the first element of the array larger than pivot element 
    (arr[i + 1], arr[end]) = (arr[end], arr[i + 1])
    # print('\n', arr)
    # we return the spot of the change 
    return i+1

def quick_sort(arr, start, end):
    
    if start<end:
        
        pivot = parition(arr, start, end)
        print(arr)
        quick_sort(arr, start, pivot-1)
        quick_sort(arr, pivot+1, end)


In [35]:
my_array = [64, 34, 25, 12, 22, 11, 90, 5]
start = 0
end = len(my_array)-1
quick_sort(my_array, start, end)
print("Sorted array:", my_array)

[5, 34, 25, 12, 22, 11, 90, 64]
[5, 34, 25, 12, 22, 11, 64, 90]
[5, 11, 25, 12, 22, 34, 64, 90]
[5, 11, 25, 12, 22, 34, 64, 90]
[5, 11, 12, 22, 25, 34, 64, 90]
Sorted array: [5, 11, 12, 22, 25, 34, 64, 90]


In [44]:
def particion(arr, start, end):
    pivot = arr[end]
    i = start-1
    for j in range(start, end):
        if arr[j]<pivot:
            i += 1 
            arr[j], arr[i] = arr[i], arr[j]
        arr[i+1], pivot = pivot, arr[i+1]
        return i+1

def QuickSort(arr, start, end):
    if start<end:
        pivot = parition(start, end)
        QuickSort(arr, start, pivot-1)
        QuickSort(arr, pivot+1, end)

In [47]:
# Generating a list of 20 random integers between 1 and 100 using numpy's randint function
import numpy as np

my_array = np.random.default_rng(seed=42).integers(1, 101, size=20)
sorted_array = sorted(my_array)
start = 0
end = len(my_array)-1
quick_sort(my_array, start, end)
print("Sorted array:", my_array)

[ 9 44 44  9 21 10 13 46 66 86 53 98 74 77 72 79 52 78 84 70]
[ 9  9 10 13 21 44 44 46 66 86 53 98 74 77 72 79 52 78 84 70]
[ 9  9 10 13 21 44 44 46 66 86 53 98 74 77 72 79 52 78 84 70]
[ 9  9 10 13 21 44 44 46 66 86 53 98 74 77 72 79 52 78 84 70]
[ 9  9 10 13 21 44 44 46 66 86 53 98 74 77 72 79 52 78 84 70]
[ 9  9 10 13 21 44 44 46 66 86 53 98 74 77 72 79 52 78 84 70]
[ 9  9 10 13 21 44 44 46 66 53 52 70 74 77 72 79 86 78 84 98]
[ 9  9 10 13 21 44 44 46 52 53 66 70 74 77 72 79 86 78 84 98]
[ 9  9 10 13 21 44 44 46 52 53 66 70 74 77 72 79 86 78 84 98]
[ 9  9 10 13 21 44 44 46 52 53 66 70 74 77 72 79 86 78 84 98]
[ 9  9 10 13 21 44 44 46 52 53 66 70 74 77 72 79 78 84 86 98]
[ 9  9 10 13 21 44 44 46 52 53 66 70 74 77 72 78 79 84 86 98]
[ 9  9 10 13 21 44 44 46 52 53 66 70 72 77 74 78 79 84 86 98]
[ 9  9 10 13 21 44 44 46 52 53 66 70 72 74 77 78 79 84 86 98]
Sorted array: [ 9  9 10 13 21 44 44 46 52 53 66 70 72 74 77 78 79 84 86 98]
